<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>aerial_robot_estimation</name>
  <version>0.0.0</version>
  <description>ROS 2 package for aerial_robot_estimation</description>
  <maintainer email="chou@dragon.t.u-tokyo.ac.jp">Bakui Chou</maintainer>
  <license>BSD-3-Clause</license>
  <author email="chou@dragon.t.u-tokyo.ac.jp">Bakui Chou</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- ROS 2 dependencies -->
  <depend>rclcpp</depend>
  <depend>pluginlib</depend>
  <depend>tf2_eigen_kdl</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>geographic_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>std_srvs</depend>
  <depend>geodesy</depend>

  <!-- Kalman filter dependency -->
  <depend>kalman_filter</depend>

  <!-- Aerial robot dependencies -->
  <depend>aerial_robot_model</depend>
  <depend>aerial_robot_msgs</depend>
  <depend>spinal</depend>

  <!-- Linters -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_cmake_cppcheck</test_depend>
  <test_depend>ament_cmake_lint_cmake</test_depend>
  <test_depend>ament_cmake_pep257</test_depend>
  <test_depend>ament_cmake_xmllint</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <pluginlib plugin="${prefix}/plugins/sensor_plugins.xml"/>
  </export>
</package>
